steps:
  - command:
    - "yarn install"
    - "yarn run test --coverage"
    label: "Run unit tests"
    plugins:
      - docker#v3.3.0:
          image: "node:7"
          always-pull: true
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"


  - command: "./auto/check-code-style"
    label: "Check code style"

  - wait

  - command: "./auto/release"
    label: "Build and Release docker image"
    branches: "master"

  - block: "Deploy"
    branches: "master"

  - command: "./auto/deploy"
    label: "Deploy"
    branches: "master"
