#! /bin/bash -ex
cd $(dirname $0)/..

CONTAINER_NAME=buildkite-demo-check-code-style

docker run --rm \
    -v $(pwd):/app \
    -e NODE_ENV=test \
    -it
    --name $CONTAINER_NAME node:8.11.3-alpine \
    bash
    # sh -c "cd /app && yarn install && yarn eslint"
    